#! /usr/local/bin/python
# -*- coding: utf-8 -*-

import sys
import os
import warnings
import datetime


sys.path.append("../")
from utils.conf import  wd,wd_cur,ai,  ai_cur
from utils.etl import ETL

warnings.filterwarnings('ignore')
os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8'

if len(sys.argv) == 1:
    dodate = (datetime.datetime.now()  - datetime.timedelta(days=1)).strftime("%Y-%m-%d")
else:
    dodate = sys.argv[1]

table_name = 'equ_financial_indicator'
file_name = 'equ_financial_indicator'

sql="""
SELECT
replace(regexp_substr(s_info_windcode,'.*?\.'),'.')  as ticker,
to_date(ann_dt ,'yyyy-mm-dd')AS anno_dt,
to_date(report_period,'yyyy-mm-dd') AS report_period,
crncy_code AS currency_cd,
S_FA_EXTRAORDINARY AS extra_ordinary,
S_FA_DEDUCTEDPROFIT AS deducted_profit,
S_FA_GROSSMARGIN AS gross_margin,
S_FA_OPERATEINCOME AS operate_income,
S_FA_INVESTINCOME AS invest_income,
S_STMNOTE_FINEXP AS stm_note_finexp,
S_STM_IS AS stm_is,
S_FA_EBIT AS ebit,
S_FA_EBITDA AS ebitda,
S_FA_FCFF AS fcff,
S_FA_FCFE AS fcfe,
S_FA_EXINTERESTDEBT_CURRENT AS ex_interest_debt_current,
S_FA_EXINTERESTDEBT_NONCURRENT AS ex_interest_debt_noncurrent,
S_FA_INTERESTDEBT AS interest_debt,
S_FA_NETDEBT AS net_debt,
S_FA_TANGIBLEASSET AS tangible_asset,
S_FA_WORKINGCAPITAL AS workingc_apital,
S_FA_NETWORKINGCAPITAL AS networki_ngcapital,
S_FA_INVESTCAPITAL AS investca_pital,
S_FA_RETAINEDEARNINGS AS retained_earnings,
S_FA_EPS_BASIC AS eps_basic,
S_FA_EPS_DILUTED AS eps_diluted,
S_FA_EPS_DILUTED2 AS eps_diluted2,
S_FA_BPS AS b_ps,
S_FA_OCFPS AS ocf_ps,
S_FA_GRPS AS gr_ps,
S_FA_ORPS AS or_ps,
S_FA_SURPLUSCAPITALPS AS surplus_capital_ps,
S_FA_SURPLUSRESERVEPS AS surplus_reserve_ps,
S_FA_UNDISTRIBUTEDPS AS un_distributed_ps,
S_FA_RETAINEDPS AS retained_ps,
S_FA_CFPS AS cf_ps,
S_FA_EBITPS AS ebit_ps,
S_FA_FCFFPS AS fcff_ps,
S_FA_FCFEPS AS fcfe_ps,
S_FA_NETPROFITMARGIN AS net_profit_margin,
S_FA_GROSSPROFITMARGIN AS gross_profit_margin,
S_FA_COGSTOSALES AS cogs_to_sales,
S_FA_EXPENSETOSALES AS expense_to_sales,
S_FA_PROFITTOGR AS profit_to_gr,
S_FA_SALEEXPENSETOGR AS sale_expense_to_gr,
S_FA_ADMINEXPENSETOGR AS admin_expense_to_gr,
S_FA_FINAEXPENSETOGR AS fina_expense_to_gr,
S_FA_IMPAIRTOGR_TTM AS impair_to_gr_ttm,
S_FA_GCTOGR AS gc_to_gr,
S_FA_OPTOGR AS op_to_gr,
S_FA_EBITTOGR AS ebit_to_gr,
S_FA_ROE AS roe,
S_FA_ROE_DEDUCTED AS roe_deducted,
S_FA_ROA2 AS roa2,
S_FA_ROA AS roa,
S_FA_ROIC AS roic,
S_FA_ROE_YEARLY AS roe_yearly_,
S_FA_ROA2_YEARLY AS roa2_yearly,
S_FA_ROE_AVG AS roe_avg,
S_FA_OPERATEINCOMETOEBT AS operate_income_to_ebt,
S_FA_INVESTINCOMETOEBT AS invest_income_to_ebt,
S_FA_NONOPERATEPROFITTOEBT AS non_operate_profit_to_ebt,
S_FA_TAXTOEBT AS tax_to_ebt,
S_FA_DEDUCTEDPROFITTOPROFIT AS deducted_profit_to_profit,
S_FA_SALESCASHINTOOR AS sales_cash_in_to_or,
S_FA_OCFTOOR AS ocf_to_or,
S_FA_OCFTOOPERATEINCOME AS ocf_to_operate_income,
S_FA_CAPITALIZEDTODA AS capitalized_to_da,
S_FA_DEBTTOASSETS AS debt_to_assets,
S_FA_ASSETSTOEQUITY AS assets_to_equity,
S_FA_DUPONT_ASSETSTOEQUITY AS dupont_assets_to_equity,
S_FA_CATOASSETS AS ca_to_assets,
S_FA_NCATOASSETS AS nca_to_assets,
S_FA_TANGIBLEASSETSTOASSETS AS tangibleassets_to_total_assets,
S_FA_INTDEBTTOTOTALCAP AS intdebt_to_total_cap,
S_FA_EQUITYTOTOTALCAPITAL AS equity_to_total_capital,
S_FA_CURRENTDEBTTODEBT AS current_debt_to_debt,
S_FA_LONGDEBTODEBT AS long_debt__to_total_debt,
S_FA_CURRENT AS current_ratio,
S_FA_QUICK AS quick,
S_FA_CASHRATIO AS cash_ratio,
S_FA_OCFTOSHORTDEBT AS ocf_to_short_debt,
S_FA_DEBTTOEQUITY AS debt_to_equity,
S_FA_EQUITYTODEBT AS equity_to_debt,
S_FA_EQUITYTOINTERESTDEBT AS equity_to_interest_debt,
S_FA_TANGIBLEASSETTODEBT AS tangible_asset_to_debt,
S_FA_TANGASSETTOINTDEBT AS tangasset_to_intdebt,
S_FA_TANGIBLEASSETTONETDEBT AS tangible_asset_to_netdebt,
S_FA_OCFTODEBT AS ocf_to_debt,
S_FA_OCFTOINTERESTDEBT AS ocf_to_interest_debt,
S_FA_OCFTONETDEBT AS ocf_to_net_debt,
S_FA_EBITTOINTEREST AS ebit_to_interest,
S_FA_LONGDEBTTOWORKINGCAPITAL AS long_debt_to_working_capital,
S_FA_EBITDATODEBT AS ebitda_to_debt,
S_FA_TURNDAYS AS turndays,
S_FA_INVTURNDAYS AS inv_turndays,
S_FA_ARTURNDAYS AS ar_turndays,
S_FA_INVTURN AS inv_turn,
S_FA_ARTURN AS ar_turn,
S_FA_CATURN AS ca_turn,
S_FA_FATURN AS fa_turn,
S_FA_ASSETSTURN AS assets_turn,
S_FA_ROA_YEARLY AS roa_yearly_,
S_FA_DUPONT_ROA AS dupont_roa,
S_STM_BS AS stm_bs,
S_FA_PREFINEXPENSE_OPPROFIT AS prefin_expense_op_profit,
S_FA_NONOPPROFIT AS non_op_profit,
S_FA_OPTOEBT AS op_to_ebt,
S_FA_NOPTOEBT AS nop_to_ebt_,
S_FA_OCFTOPROFIT AS ocf_to_profit,
S_FA_CASHTOLIQDEBT AS cash_to_liqdebt,
S_FA_CASHTOLIQDEBTWITHINTEREST AS cash_to_liqdebt_withinterest,
S_FA_OPTOLIQDEBT AS op_to_liqdebt,
S_FA_OPTODEBT AS op_to_debt_,
S_FA_ROIC_YEARLY AS roic_yearly,
S_FA_TOT_FATURN AS tot_faturn_,
S_FA_PROFITTOOP AS profit_to_op,
S_QFA_OPERATEINCOME AS q_operate_income,
S_QFA_INVESTINCOME AS q_invest_income,
S_QFA_DEDUCTEDPROFIT AS q_deducted_profit,
S_QFA_EPS AS q_eps,
S_QFA_NETPROFITMARGIN AS q_netprofit_margin,
S_QFA_GROSSPROFITMARGIN AS q_gross_profit_margin,
S_QFA_EXPENSETOSALES AS q_expense_to_sales,
S_QFA_PROFITTOGR AS q_profit_to_gr,
S_QFA_SALEEXPENSETOGR AS q_sale_expense_to_gr,
S_QFA_ADMINEXPENSETOGR AS q_admin_expense_to_gr,
S_QFA_FINAEXPENSETOGR AS q_fina_expense_to_gr,
S_QFA_IMPAIRTOGR_TTM AS q_impair_to_gr_ttm,
S_QFA_GCTOGR AS q_gc_to_gr,
S_QFA_OPTOGR AS q_op_to_gr,
S_QFA_ROE AS q_roe,
S_QFA_ROE_DEDUCTED AS q_roe_deducted,
S_QFA_ROA AS q_roa,
S_QFA_OPERATEINCOMETOEBT AS q_operate_income_to_ebt,
S_QFA_INVESTINCOMETOEBT AS q_invest_income_to_ebt,
S_QFA_DEDUCTEDPROFITTOPROFIT AS q_deducted_profit_to_profit,
S_QFA_SALESCASHINTOOR AS q_sales_cashin_to_or,
S_QFA_OCFTOSALES AS q_ocf_to_sales,
S_QFA_OCFTOOR AS ocf_to_or_,
S_FA_YOYEPS_BASIC AS yoy_eps_basic,
S_FA_YOYEPS_DILUTED AS yoy_eps_diluted,
S_FA_YOYOCFPS AS yoy_ocf_ps,
S_FA_YOYOP AS yoy_op,
S_FA_YOYEBT AS yoy_ebt,
S_FA_YOYNETPROFIT AS yoy_netprofit,
S_FA_YOYNETPROFIT_DEDUCTED AS yoy_netprofit_deducted,
S_FA_YOYOCF AS yoy_ocf,
S_FA_YOYROE AS yoy_roe,
S_FA_YOYBPS AS yoy_bps,
S_FA_YOYASSETS AS yoy_assets,
S_FA_YOYEQUITY AS yoy_equity_yearly,
S_FA_YOY_TR AS yoy_tr,
S_FA_YOY_OR AS yoy_or,
S_QFA_YOYGR AS q_yoy_gr,
S_QFA_CGRGR AS q_cgr_gr,
S_QFA_YOYSALES AS q_yoy_sales,
S_QFA_CGRSALES AS q_cgr_sales,
S_QFA_YOYOP AS q_yoy_op,
S_QFA_CGROP AS q_cgr_op,
S_QFA_YOYPROFIT AS q_yoy_profit,
S_QFA_CGRPROFIT AS q_cgr_profit,
S_QFA_YOYNETPROFIT AS q_yoy_net_profit,
S_QFA_CGRNETPROFIT AS q_cgr_netprofit,
S_FA_YOY_EQUITY AS yoy_equity,
RD_EXPENSE AS rd_expense,
WAA_ROE AS waa_roe,
S_INFO_COMPCODE AS comp_code，
'wind' as    src_channel,
1 as    src_table,
object_id as    src_object_id,
s_info_windcode  as         src_code,
opdate  as    src_opdate
FROM eterminal.ASHAREFINANCIALINDICATOR  where   to_char(opdate,'YYYY-MM-DD') >='%s'
""" % (dodate)

cols=""" ticker,
anno_dt,
report_period,
 currency_cd,
 extra_ordinary,
 deducted_profit,
 gross_margin,
 operate_income,
 invest_income,
 stm_note_finexp,
 stm_is,
 ebit,
 ebitda,
 fcff,
 fcfe,
ex_interest_debt_current,
 ex_interest_debt_noncurrent,
 interest_debt,
 net_debt,
 tangible_asset,
 workingc_apital,
 networki_ngcapital,
 investca_pital,
 retained_earnings,
 eps_basic,
 eps_diluted,
 eps_diluted2,
 b_ps,
 ocf_ps,
 gr_ps,
 or_ps,
 surplus_capital_ps,
 surplus_reserve_ps,
 un_distributed_ps,
retained_ps,
 cf_ps,
ebit_ps,
 fcff_ps,
 fcfe_ps,
 net_profit_margin,
 gross_profit_margin,
 cogs_to_sales,
 expense_to_sales,
profit_to_gr,
 sale_expense_to_gr,
 admin_expense_to_gr,
 fina_expense_to_gr,
 impair_to_gr_ttm,
 gc_to_gr,
op_to_gr,
 ebit_to_gr,
 roe,
 roe_deducted,
 roa2,
 roa,
 roic,
 roe_yearly_,
 roa2_yearly,
 roe_avg,
 operate_income_to_ebt,
 invest_income_to_ebt,
 non_operate_profit_to_ebt,
 tax_to_ebt,
 deducted_profit_to_profit,
 sales_cash_in_to_or,
 ocf_to_or,
 ocf_to_operate_income,
 capitalized_to_da,
 debt_to_assets,
assets_to_equity,
 dupont_assets_to_equity,
 ca_to_assets,
nca_to_assets,
 tangibleassets_to_total_assets,
intdebt_to_total_cap,
 equity_to_total_capital,
 current_debt_to_debt,
 long_debt__to_total_debt,
 current_ratio,
 quick,
 cash_ratio,
 ocf_to_short_debt,
 debt_to_equity,
 equity_to_debt,
 equity_to_interest_debt,
 tangible_asset_to_debt,
 tangasset_to_intdebt,
 tangible_asset_to_netdebt,
 ocf_to_debt,
 ocf_to_interest_debt,
 ocf_to_net_debt,
 ebit_to_interest,
long_debt_to_working_capital,
ebitda_to_debt,
 turndays,
 inv_turndays,
 ar_turndays,
 inv_turn,
 ar_turn,
ca_turn,
 fa_turn,
 assets_turn,
roa_yearly_,
 dupont_roa,
 stm_bs,
 prefin_expense_op_profit,
non_op_profit,
 op_to_ebt,
 nop_to_ebt_,
ocf_to_profit,
 cash_to_liqdebt,
 cash_to_liqdebt_withinterest,
 op_to_liqdebt,
 op_to_debt_,
 roic_yearly,
 tot_faturn_,
 profit_to_op,
 q_operate_income,
q_invest_income,
 q_deducted_profit,
 q_eps,
 q_netprofit_margin,
q_gross_profit_margin,
 q_expense_to_sales,
q_profit_to_gr,
 q_sale_expense_to_gr,
 q_admin_expense_to_gr,
q_fina_expense_to_gr,
 q_impair_to_gr_ttm,
 q_gc_to_gr,
 q_op_to_gr,
q_roe,
 q_roe_deducted,
 q_roa,
 q_operate_income_to_ebt,
 q_invest_income_to_ebt,
 q_deducted_profit_to_profit,
q_sales_cashin_to_or,
 q_ocf_to_sales,
ocf_to_or_,
 yoy_eps_basic,
 yoy_eps_diluted,
 yoy_ocf_ps,
 yoy_op,
 yoy_ebt,
 yoy_netprofit,
 yoy_netprofit_deducted,
 yoy_ocf,
 yoy_roe,
yoy_bps,
 yoy_assets,
 yoy_equity_yearly,
 yoy_tr,
 yoy_or,
 q_yoy_gr,
 q_cgr_gr,
 q_yoy_sales,
 q_cgr_sales,
q_yoy_op,
 q_cgr_op,
 q_yoy_profit,
 q_cgr_profit,
q_yoy_net_profit,
 q_cgr_netprofit,
yoy_equity,
 rd_expense,
 waa_roe,
 comp_code,
 src_channel,
 src_table,
 src_object_id,
 src_code,
 src_opdate
"""

unique_key = "anno_dt,report_period,src_code"

print(sql)
etl = ETL(src_cur=wd_cur,
          src_conn=wd,
          tgt_cur=ai_cur,
          tgt_conn=ai,
          sql=sql,
          table_name=table_name,
          columns=cols,
          unique_key=unique_key)

# 加载数据
etl.dump_data(file_name)

# 写入数据
etl.import_data(file_name)

#etl.update_unique_id()
wd_cur.close()
ai_cur.close()
wd.close()
ai.close()
